// Mocks generated by Mockito 5.1.0 from annotations
// in paymint/test/firo_wallet_tests.dart.
// Do not manually edit this file.

// @dart=2.9

import 'package:mockito/mockito.dart' as _i1;
import 'package:paymint/electrumx_rpc/cached_electrumx.dart' as _i3;
import 'package:paymint/electrumx_rpc/electrumx.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ElectrumX].
///
/// See the documentation for Mockito's code generation for more information.
class MockElectrumX extends _i1.Mock implements _i2.ElectrumX {
  MockElectrumX() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [CachedElectrumX].
///
/// See the documentation for Mockito's code generation for more information.
class MockCachedElectrumX extends _i1.Mock implements _i3.CachedElectrumX {
  MockCachedElectrumX() {
    _i1.throwOnMissingStub(this);
  }
}
