// Mocks generated by Mockito 5.1.0 from annotations
// in paymint/test/model_json_mapping_tests/type_adapter_tests/utxo_model_adapter_test.dart.
// Do not manually edit this file.

// @dart=2.9

import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [BinaryReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockBinaryReader extends _i1.Mock implements _i2.BinaryReader {
  MockBinaryReader() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [BinaryWriter].
///
/// See the documentation for Mockito's code generation for more information.
class MockBinaryWriter extends _i1.Mock implements _i2.BinaryWriter {
  MockBinaryWriter() {
    _i1.throwOnMissingStub(this);
  }
}
