name: paymint
description: Paymint client

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.5+15

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

  lelantus:
    path: ./crypto_plugins/flutter_liblelantus

  firo_flutter:
    git:
      url: https://github.com/cypherstack/firo_flutter.git
      ref: update
  #    path: ./crypto_plugins/firo_flutter

  # Utility plugins
  provider: ^6.0.1
  http: ^0.13.4
  local_auth: ^1.1.10
  permission_handler: ^8.3.0

  # Bitcoin plugins
  bip39: ^1.0.3
  bip32: ^2.0.0

  # Storage plugins
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8

  # UI/Component plugins
  animations: ^2.0.2
  toast: ^0.1.5
  flare_flutter: ^3.0.2
  google_fonts: ^2.2.0
  pretty_qr_code: ^2.0.2
  url_launcher: ^6.0.5
  flutter_svg: ^1.0.1
  flutter_feather_icons: ^2.0.0+1
  flutter_spinkit: ^5.1.0
  decimal: ^2.1.0
  event_bus: ^2.0.0
  uuid: ^3.0.5
  flutter_rounded_date_picker: ^2.0.2
  crypto: ^3.0.1
  jsonrpc2: ^3.0.1
  barcode_scan2: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  hive_generator: ^1.1.2
  dependency_validator: ^3.1.2
  hive_test: ^1.0.1
  mockito: ^5.1.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter_native_splash:
  image: assets/images/splash.png
  color: "262D4A"
  android_disable_fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/splash.png
    - assets/images/logo.png
    - assets/rive/success.flr
    - assets/icon/icon.png
    - google_fonts/
    - assets/svg/check-circle.svg
    - assets/svg/check-circle2.svg
    - assets/svg/chevronLeft.svg
    - assets/svg/chevron-right.svg
    - assets/svg/close.svg
    - assets/svg/copy.svg
    - assets/svg/groupLogo.svg
    - assets/svg/menu.svg
    - assets/svg/radio.svg
    - assets/svg/wallet.svg
    - assets/svg/x.svg
    - assets/svg/book-open.svg
    - assets/svg/qr-code.svg
    - assets/svg/search.svg
    - assets/svg/splash.svg
    - assets/svg/plus.svg
    - assets/svg/log-out.svg
    - assets/svg/key.svg
    - assets/svg/settings.svg
    - assets/svg/dollar-sign.svg
    - assets/svg/empty-address-list.svg
    - assets/svg/empty-tx-list.svg
    - assets/svg/calendar.svg
    - assets/svg/radio-disconnected.svg
    - assets/svg/refresh-cw.svg
    - assets/svg/more-vertical.svg
    - assets/svg/globe.svg
    - assets/svg/check-circle3.svg
    - assets/svg/copy-2.svg
    - assets/svg/download-2.svg
    - assets/svg/edit-4.svg
    - assets/svg/fingerprint.svg
    - assets/svg/lock.svg
    - assets/svg/menu-2.svg
    - assets/svg/node.svg
    - assets/svg/upload-2.svg
    - assets/svg/usd-circle.svg
    - assets/svg/address-contact.svg
    - assets/svg/eye.svg
    - assets/svg/wallet-2.svg
    - assets/svg/clipboard.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
