// Mocks generated by Mockito 5.1.0 from annotations
// in paymint/test/screen_tests/transaction_subviews/transaction_search_view_screen_test.dart.
// Do not manually edit this file.

// @dart=2.9

import 'package:mockito/mockito.dart' as _i1;
import 'package:paymint/services/address_book_service.dart' as _i2;
import 'package:paymint/services/notes_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AddressBookService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressBookService extends _i1.Mock
    implements _i2.AddressBookService {}

/// A class which mocks [NotesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesService extends _i1.Mock implements _i3.NotesService {}
